global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'multum'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'multum:9091' ]

