name: Run build on release
'on':
  release:
    types: [ released ]

jobs:
  release_client:
    name: Release client
    runs-on: ubuntu-latest
    steps:
      - run: |
          e="ver="
          ver=$(echo "${{ github.event.release.tag_name }}")
          echo "${e}${ver}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle permission
        run: chmod +x ./gradlew
      - name: Build client
        run: ./gradlew :modules:multum-client:jar -Pversion=${{ env.ver }}
      - name: 'Upload backend artifact'
        uses: actions/upload-artifact@v3
        with:
          name: multum-client
          path: modules/multum-client/build/libs
          retention-days: 5
      - name: Upload backend to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: modules/multum-client/build/libs/multum-client-${{ env.ver }}.jar
          asset_name: multum-client-${{ env.ver }}.jar
